
name: pytest

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: py env
      uses: actions/setup-python@v2
      with:
        python-version: '3.11.4'

    - name: requirements install
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: pytest app
      run: |
        python -m test_app

    - name: Docker image
      if: ${{ success() }}
      run: |
        docker build -t hurray .
